[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gettext']

[phases.build]
cmds = [
    'python manage.py compilemessages --ignore=venv --ignore=env',
    'python manage.py collectstatic --noinput',
    'python manage.py migrate --noinput'
]

[start]
cmd = 'gunicorn backend.wsgi:application'
